### ISSUE TITLE
Review draft proposal

### ISSUE THREAD

**Issue by deebuls** [RnDProjectsDeebul/NandhiniMathivananRnD#2]
Mai 2 review draft proposal

**Comment by nandhini30** [comment]
[R.D_PROPOSAL.pdf](https://github.com/RnDProjectsDeebul/NandhiniMathivananRnD/files/8641774/R.D_PROPOSAL.pdf)

**Comment by deebuls** [comment]
[R.D_PROPOSAL_revieweDeebul.pdf](https://github.com/RnDProjectsDeebul/NandhiniMathivananRnD/files/8668225/R.D_PROPOSAL_revieweDeebul.pdf)

First of all :+1 Great job . Way better than the previous . 

Biggest problem areas now is problem statement and  state-of-art . 

Introduction minor modifications.

**Comment by nandhini30** [comment]
[R_D_PROPOSAL_Uncertainty_Estimation (2).pdf](https://github.com/RnDProjectsDeebul/NandhiniMathivananRnD/files/8684740/R_D_PROPOSAL_Uncertainty_Estimation.2.pdf)

**Comment by deebuls** [comment]
I will send feedback, in the mean time you send a copy to the Professor.

**Comment by nandhini30** [comment]
proposal submitted
