### ISSUE TITLE
A proposal for a valid research question for the literature search - Loss function 

### ISSUE THREAD

**Issue by deebuls** [RnDProjectsDeebul/NandhiniMathivananRnD#5]
For the RQ of SLR of keypoint detection, I already told you to have separate sub-questions for dataset, task, etc.
There is an additional one which is required which is  **loss function**?
Loss function is more important as it will give you and answer to what uncertainty estimation can be used. 

So the research question set can be :
Strucutred literature survey of keypoint detection:
RQ1.1 : What are the different papers in keypoint detection
RQ1.2 : Which are the different tasks  are solved using keypoint detection
RQ1.3 : Which datasets are available for each keypoint detection task?
RQ1.4 : Which loss functions are used for keypoint detection task ?

This can be answered in a table like this 
| Paper  |Task   | dataset  |loss function   | any other important metric  |
|---|---|---|---|---|
|   [1] | T1, T2, T3]  | [D1, D2, D3]   | [L1, L2, L3]  | [.....]    |
|   |   |   |   |   |
|   |   |   |   |   |

The table then can also be converted to a graph for better understanding . Like here 
https://towardsdatascience.com/create-a-graph-database-in-neo4j-using-python-4172d40f89c4

Or the graph can be the mind - map

**Comment by nandhini30** [comment]
Thanks for the input. I have added the sub-questions in the proposal.
[R_D_PROPOSAL_Uncertainty_Estimation.pdf](https://github.com/RnDProjectsDeebul/NandhiniMathivananRnD/files/8687201/R_D_PROPOSAL_Uncertainty_Estimation.pdf)
